name: Python App

on:
  push:
    branches:
      - main  # Jalankan setiap kali ada push ke branch `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Gunakan versi Python yang sama

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test Import Matplotlib
      run: |
        python -c "import matplotlib; print(matplotlib.__version__)"
